### ISSUE TITLE
Question, not an issue

### ISSUE THREAD

**Issue by toxic-ig** [ex0dus-0x/D0xk1t#7]
Why do the screenshots show a version that is not available to the public? Could you release that version?

**Comment by ex0dus-0x** [comment]
That revision was actually a depreciated version.

I took out some of the extra functionality because 1) it was just aesthetic eye candy that didn't provide any core functionality 2) Some of the code was broken.

I've been implementing a yaml parser with the database, so you will definitely see changes soon.
